# Generated by Django 2.2 on 2019-05-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_userextended_progress_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='chapter',
            field=models.CharField(blank=True, choices=[('33', '33'), ('30', '30'), ('31', '31'), ('35', '35'), ('1606', '1606')], max_length=4, null=True),
        ),
    ]
