# Generated by Django 2.2 on 2019-05-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20190430_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='is_firsttime',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='is_student',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
