# Generated by Django 2.2 on 2019-05-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20190430_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='is_firsttime',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='is_student',
            field=models.BooleanField(null=True),
        ),
    ]
