# Generated by Django 2.2 on 2019-05-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20190430_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='is_student',
            field=models.BooleanField(),
        ),
    ]
