# Generated by Django 2.1.7 on 2019-04-30 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20190428_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certs', to=settings.AUTH_USER_MODEL),
        ),
    ]
