# Generated by Django 2.2 on 2019-05-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20190430_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='CertifiedBy',
            field=models.CharField(default='None(COE)', max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='CertifiedBy2',
            field=models.CharField(default='None(Info Sheet)', max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='CertifiedBy3',
            field=models.CharField(default='None(Student Responsibility)', max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='CertifiedBy4',
            field=models.CharField(default='None(Date Tuition)', max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='CertifiedBy5',
            field=models.CharField(default='None(Concise Student Schedule)', max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='CertifiedBy6',
            field=models.CharField(default='None(Degree Audit)', max_length=30),
        ),
    ]
