# Generated by Django 2.2 on 2019-05-01 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20190430_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certs', to=settings.AUTH_USER_MODEL),
        ),
    ]
